### ISSUE TITLE
backend [final build]

### ISSUE THREAD

**Issue by jasyyang** [camtheman256/6.1040-final-project#16]
- [x] **[TODO]** PUTs for /requests (status updating for: not addressed/in progress/done)
- [ ] *[aspirational]* ~~geolocation validator for checkin (/checkin/middleware.ts + add in optional property in checkin POST request for lat/long)~~
- [x] **[TODO]** upvote functionality #42 
- [x] **[TODO]** user check-in leaderboard for spaces #41 
- [ ] *[aspirational]* ~~check-in counts for a user-> list of spaces that I have checked into before and # of times?~~
- [x] **[TODO]** clean up yesterday check-in behavior + docs #40 
- [x] **[TODO]** populate users and spaces and *requests?* across the board + docs #39

**Comment by camtheman256** [comment]
because this issue is for final build, im gonna close it as final build is done lol
